# Generated by Django 6.0 on 2025-12-22 15:06

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trading_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('document', models.CharField(max_length=50, unique=True)),
                ('address', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('coverage_area', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
